name: iOSTest

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        xcodebuild test \
          -project AutoPreviewable.xcodeproj \
          -scheme AutoPreviewableTests \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone X,OS=13.3"
